[project]
name = "ai-powered-multi-agent-system-for-automobile-warranty-fraud-detection-investigation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "langchain-openai>=1.6.2",
    "langgraph>=1.2.11",
    "pandas>=3.0.6",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.3",
]
